{{- if .Values.deploySecret -}}
apiVersion: v1
kind: Secret
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD | b64enc }}
metadata:
  name: label-studio-password
  namespace: {{ .Release.Namespace  }}
{{- end -}}
