apiVersion: v2
name: label-studio
appVersion: 1.5.5
version: 1.3.8
description: A Helm chart for label-studio community edition, Open source text annotation tool for machine learning practitioner.
home: https://labelstud.io/
icon: https://raw.githubusercontent.com/heartexlabs/label-studio/master/images/ls_github_header.png
sources:
  - https://github.com/heartexlabs/label-studio
maintainers:
  - name: mehdibenamor
    email: mehdi.benamor@uni-passau.de
kubeVersion: ">= 1.14.0-0"
keywords:
  - annotation
  - ml
  - nlp
  - text
  - machine-learning
annotations:
  artifacthub.io/images: |
    - name: label-studio-ce
      image: heartexlabs/label-studio:1.4.0
