apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: label-studio
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: CqqSAXP7NeYz43de


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: labelstudio-config
  namespace: label-studio
  labels:
    app: labelstudio
data:
  DJANGO_DB: default
  POSTGRES_NAME: postgresdb
  POSTGRE_PORT: "5432"
  POSTGRE_HOST: postgres.label-studio.svc.cluster.local
  LABEL_STUDIO_HOST: https://label-studio.pads.fim.uni-passau.de
  LABEL_STUDIO_COPY_STATIC_DATA: "false"